version: '3.8'
services:
  couchbase:
    container_name: db
    image: couchbase:community-7.2.0
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 8095:8095
      - 8096:8096
      - 8097:8097
      - 9123:9123
      - 11207:11207
      - 11210:11210
      - 11280:11280
      - 18091:18091
      - 18092:18092
      - 18093:18093
      - 18094:18094
      - 18095:18095
      - 18096:18096
      - 18097:18097
    networks:
      - cb
    deploy:
      resources:
        limits:
          memory: 2G

  sync-gateway:
    container_name: db_sync_gw
    image: couchbase/sync-gateway:3.1.1-community
    ports:
      - 4984:4984
      - 4985:4985
    volumes:
      - ./sync-gateway:/tmp/config:ro,cached
    command: /tmp/config/config-gateway.json
    entrypoint: [ "/tmp/config/wait-for-couchbase-server.sh" ]
    networks:
      - cb
    deploy:
      resources:
        limits:
          memory: 1G

networks:
  cb:
    external:
      name: couchbase_realworld
