name: Run Postman tests against Capella
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
  - cron: "0 11 * * 0"
env:
  COUCHBASE_CONNECTIONSTRING: ${{ secrets.DB_ENDPOINT }}
  COUCHBASE_USERNAME: ${{ secrets.DB_USERNAME }}
  COUCHBASE_PASSWORD: ${{ secrets.DB_PASSWORD }}
  COUCHBASE_DEFAULTBUCKET: ${{ secrets.DB_BUCKET }}
  COUCHBASE_DEFAULTSCOPE:  ${{ vars.GITHUB_HEAD_REF }}
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['17']
    steps:
    - name: Update repositories
      run: |
        apt update || echo "apt-update failed" # && apt -y upgrade
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'
    - uses: actions/checkout@v2
    - name: Postman Tests
      run: |
        mvn --batch-mode --update-snapshots -B spring-boot:run --file pom.xml verify 
        chmod +x ./postman/run-api-tests.sh
        npm start &
        APIURL="http://127.0.0.1:4000/api" ./postman/run-api-tests.sh

