name: Run Postman tests against Capella
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
  - cron: "0 11 * * 0"
env:
  COUCHBASE_CONNECTIONSTRING: ${{ secrets.COUCHBASE_CONNECTIONSTRING }}
  COUCHBASE_USERNAME: ${{ secrets.COUCHBASE_USERNAME }}
  COUCHBASE_PASSWORD: ${{ secrets.COUCHBASE_PASSWORD }}
  COUCHBASE_DEFAULTBUCKET: ${{ secrets.COUCHBASE_DEFAULTBUCKET }}
  COUCHBASE_DEFAULTSCOPE:  ${{ vars.GITHUB_HEAD_REF || '_default' }}
  COUCHBASE_USECAPELLA: ${{ vars.COUCHBASE_USECAPELLA }}
  APIURL: "http://127.0.0.1:8080/api"
jobs:
  tests:
    runs-on: ubuntu-latest
    environment: CapellaDRTenant
    timeout-minutes: 15
    strategy:
      matrix:
        java-version: ['17']
    steps:
    - name: Update repositories
      run: |
        apt update || echo "apt-update failed" # && apt -y upgrade
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'
    - uses: actions/checkout@v3
    - name: Postman Tests
      run: |
        mvn --batch-mode --update-snapshots -B spring-boot:run --file pom.xml verify  &
        chmod +x ./postman/run-api-tests.sh ./testConnection.sh
        timeout 5m ./testConnection.sh $APIURL/articles
        ./postman/run-api-tests.sh

